# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=32, null=True, verbose_name='分数')),
                ('content', models.TextField(null=True, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='班级名')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='问题')),
                ('type', models.IntegerField(choices=[(1, '单选'), (2, '打分'), (3, '建议')], verbose_name='类型')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('cls', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app01.ClassList', verbose_name='所属班级')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='问卷名')),
                ('cls', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app01.ClassList', verbose_name='问卷班级')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
        ),
        migrations.AddField(
            model_name='surveyinfo',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app01.User', verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='question',
            name='surveyInfo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app01.SurveyInfo', verbose_name='所属问卷'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Question', verbose_name='某个问题'),
        ),
        migrations.AddField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Student', verbose_name='某个学生'),
        ),
    ]
