# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='num',
            field=models.IntegerField(default=1, verbose_name='班级人数'),
            preserve_default=False,
        ),
    ]
