# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_classlist_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, '单选'), (2, '打分(1~10分)'), (3, '建议')], verbose_name='类型'),
        ),
    ]
